name: controlled_browser
description: Controlled browser app with remote access management
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Core dependencies
  webview_flutter: ^4.4.2
  http: ^1.1.0
  shared_preferences: ^2.2.2
  uuid: ^4.1.0
  
  # UI dependencies
  cupertino_icons: ^1.0.6
  flutter_spinkit: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # App icons
  assets:
    - assets/images/
  
  # App launcher icon
  # flutter_icons:
  #   android: "launcher_icon"
  #   image_path: "assets/icon/icon.png"