# .github/workflows/build-android.yml
name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Setup Java JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'
        
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.0'
        channel: 'stable'
        
    - name: Get Flutter Dependencies
      working-directory: ./flutter-app
      run: flutter pub get
      
    - name: Run Flutter Doctor
      run: flutter doctor -v
      
    - name: Build APK (Debug)
      working-directory: ./flutter-app
      run: flutter build apk --debug
      
    - name: Build APK (Release)
      working-directory: ./flutter-app
      run: flutter build apk --release
      
    - name: Upload Debug APK
      uses: actions/upload-artifact@v3
      with:
        name: controlled-browser-debug.apk
        path: flutter-app/build/app/outputs/flutter-apk/app-debug.apk
        
    - name: Upload Release APK
      uses: actions/upload-artifact@v3
      with:
        name: controlled-browser-release.apk
        path: flutter-app/build/app/outputs/flutter-apk/app-release.apk
        
    - name: Create GitHub Release
      if: github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.run_number }}
        name: Controlled Browser v${{ github.run_number }}
        files: |
          flutter-app/build/app/outputs/flutter-apk/app-debug.apk
          flutter-app/build/app/outputs/flutter-apk/app-release.apk
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}